/**
 * autoViewer CAD 可用字体清单 (镜像 001 插件扫描 static/fonts/{shx,ttf} 目录生成的 window.CAD_FONT_LIST)。
 * 由 demo 官方 v1.11 包的字体目录导出, 顺序保持与官方一致。
 */
export const AUTO_VIEWER_CAD_FONTS = [
  "ROMANC__.TTF", "ISOCP2__.TTF", "Artifakt Element Medium Italic.ttf", "mtproxy2.ttf", "Artifakt Element Light Italic.ttf", "swisseb.ttf",
  "swisscli.ttf", "Artifakt Element Light.ttf", "ISOCP___.TTF", "SYMUSIC_.TTF", "Artifakt Element Book Italic.ttf", "dutcheb.ttf",
  "TECHNIC_.TTF", "Artifakt Element Bold Italic.ttf", "Verdana.ttf", "ROMABI__.TTF", "ISOCP3__.TTF", "ISOCTEUR.TTF",
  "swissi.ttf", "Artifakt Element Italic.ttf", "PANROMAN.TTF", "ROMANS__.TTF", "SANSSO__.TTF", "Artifakt Element Thin Italic.ttf",
  "ITALICC_.TTF", "swiss.ttf", "Artifakt Element Regular.ttf", "MTPROXY9.TTF", "GOTHICG_.TTF", "dutchi.ttf",
  "Eurro___.ttf", "MTPROXY5.TTF", "swissci.ttf", "swissko.ttf", "swisse.ttf", "ISOCT3__.TTF",
  "SYMAP___.TTF", "ITALIC__.TTF", "monosi.ttf", "GOTHICI_.TTF", "Roboto-Light.ttf", "fang-song.ttf",
  "SCRIPTC_.TTF", "monosbi.ttf", "SYASTRO_.TTF", "swissck.ttf", "CITYB___.TTF", "Artifakt Element Heavy.ttf",
  "TXT_____.TTF", "SUPEF___.TTF", "swisski.ttf", "MTPROXY8.TTF", "bgothl.ttf", "ROMAB___.TTF",
  "comsc.ttf", "SANSSBO_.TTF", "umath.ttf", "ISOCT2__.TTF", "Artifakt Element Medium.ttf", "swisscki.ttf",
  "MTPROXY4.TTF", "swissc.ttf", "swissb.ttf", "COUNB___.TTF", "ITALICT_.TTF", "dutchbi.ttf",
  "monosb.ttf", "ISOCTEUI.TTF", "Artifakt Element Thin.ttf", "vinet.ttf", "MTPROXY3.TTF", "Artifakt Element Hair Italic.ttf",
  "bgothm.ttf", "GREEKC__.TTF", "swissbi.ttf", "monos.ttf", "swissek.ttf", "ISOCPEUR.TTF",
  "COMPLEX_.TTF", "swisscl.ttf", "compi.ttf", "swissbo.ttf", "swisscbi.ttf", "ROMAND__.TTF",
  "Artifakt Element Heavy Italic.ttf", "SIMPLEX_.TTF", "SYMATH__.TTF", "GDT_____.TTF", "ISOCPEUI.TTF", "dutchb.ttf",
  "swisscbo.ttf", "Artifakt Element Bold.ttf", "Eurr____.ttf", "GOTHICE_.TTF", "swissel.ttf", "GREEKS__.TTF",
  "Artifakt Element Book.ttf", "mtproxy1.ttf", "swissk.ttf", "swissl.ttf", "TECHL___.TTF", "MTPROXY7.TTF",
  "Artifakt Element Black.ttf", "MONOTXT_.TTF", "MTPROXY6.TTF", "TECHB___.TTF", "SCRIPTS_.TTF", "SANSS___.TTF",
  "ROMANTIC.TTF", "swisscb.ttf", "arial.ttf", "SYMETEO_.TTF", "Artifakt Element Black Italic.ttf", "ROMAI___.TTF",
  "swissli.ttf", "ISOCT___.TTF", "ROMANT__.TTF", "dutch.ttf", "Artifakt Element Hair.ttf", "stylu.ttf",
  "SANSSB__.TTF", "GENPRESE.SHX", "AMGDTANS DWE Edits.shx", "g13f12w.shx", "bigfont.shx", "AcadEref.shx",
  "syastro.shx", "romand.shx", "bold.shx", "whgdtxt.shx", "italic.shx", "AMGDT DWE Edits.shx",
  "wlc-e2.shx", "geniso12.shx", "isocp2.shx", "greeks.shx", "MONOTXT8.shx", "gothice.shx",
  "GENLTSHP.SHX", "iges1001.shx", "whgtxt.shx", "gothicg.shx", "romanc.shx", "complex.shx",
  "dim.shx", "hztxt.shx", "romans.shx", "CDM_NC.shx", "italict.shx", "scriptc.shx",
  "gdt.shx", "g13f12d.shx", "amgdtans.shx", "exthalf2.shx", "italicc.shx", "romant.shx",
  "ITALIC8.shx", "EMPTY.SHX", "g12f13.shx", "wlc-e1.shx", "wlc-c.shx", "whtmtxt.shx",
  "symap.shx", "isoct2.shx", "aaa.shx", "isoct3.shx", "gothici.shx", "greekc.shx",
  "special.shx", "monotxt.shx", "gbenor.shx", "r12eqm.shx", "amgdt.shx", "aehalf.shx",
  "gbeitc.shx", "gdt-ic.shx", "isocp3.shx", "ltypeshp.shx", "extfont.shx", "spec_bar.shx",
  "iges1002.shx", "hand1.shx", "scripts.shx", "gbcbig.shx", "es.shx", "isocp.shx",
  "chineset.shx", "SIMPLEX8.shx", "GENISO.shx", "AMDTSymbols.shx", "extslim2.shx", "symusic.shx",
  "iges1003.shx", "times.shx", "st.shx", "symath.shx", "tssdeng.shx", "Cdm.shx",
  "extfont2.shx", "simplex.shx", "isoct.shx", "@extfont2.shx", "spec_sl.shx", "ISO.shx",
  "whtgtxt.shx", "txt.shx", "timesout.shx", "symeteo.shx", "pc.shx", "thenor.shx",
];
